model:
  base_learning_rate: 1.0e-5
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: image
    ocm_dpm: false
    learn_sigma: true
    var_type: LearnedRange
    image_size: 64
    channels: 3
    # monitor: val/loss_simple_ema
    monitor: val/loss
    use_ema: false
    scheduler_config:
      target: ldm.lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps:
        - 1000
        cycle_lengths:
        - 10000000000000
        f_start:
        - 1.0e-06
        f_max:
        - 1.0
        f_min:
        - 1.0
    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 64
        in_channels: 3
        out_channels: 6 # 3 for x0 and 3 for logvar
        model_channels: 224
        attention_resolutions: [8, 4, 2]
        num_res_blocks: 2
        channel_mult: [ 1,2,3,4 ]
        num_heads: 32
    first_stage_config:
      target: ldm.models.autoencoder.VQModelInterface
      params:
        embed_dim: 3
        n_embed: 8192
        ckpt_path: /home/csgrad/mbhosale/phd/Pathdiff/PathLDM/models/first_stage_models/vq-f4/model.ckpt
        ddconfig:
          double_z: false
          z_channels: 3
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    cond_stage_config: __is_unconditional__
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 32
    num_workers: 12
    wrap: false
    train:
      target: ldm.data.chess.ChessDatasetUncond
      params:
        config:
          root: "/data_local1/mbhosale/Diffhaul/Chess" #"/data_local1/mbhosale/Diffhaul/Chess" #"/data_local1/mbhosale/Diffhaul/Chess"
          split: train
          crop_size: 256
          inference: False
          p_uncond: 0.1
    validation:
      target: ldm.data.chess.ChessDatasetUncond
      params:
        config:
          root: "/data_local1/mbhosale/Diffhaul/Chess" #"/data_local1/mbhosale/Diffhaul/Chess" #"/data_local1/mbhosale/Diffhaul/Chess/"
          split: test
          crop_size: 256
          inference: False
lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 1000
        max_images: 8
        increase_log_steps: False
  trainer:
    benchmark: True
    accumulate_grad_batches: 2
    accelerator: ddp
    gpus: -1
